openapi: 3.0.2
info:
  title: Pereval API
  version: 0.1

paths:
  /users:
    get:
      summary: Get a list of users
      operationId: listUsers
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
      tags:
        - users

  /users/{id}:
    get:
      summary: Get a user by ID
      operationId: getUserById
      parameters:
        - name: id
          in: path
          required: true
          description: ID of the user
          schema:
            type: integer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
      tags:
        - user_by_id

  /coordinates:
    get:
      summary: Get a list of coordinates
      operationId: listCoordinates
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Coordinates'
      tags:
        - coordinates

  /coordinates/{id}:
    get:
      summary: Get a coordinates by ID
      operationId: getCoordinatesById
      parameters:
        - name: id
          in: path
          required: true
          description: ID of the coordinates
          schema:
            type: integer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Coordinates'
      tags:
        - coordinates_by_id

  /images:
    get:
      summary: Get a list of images
      operationId: listImages
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Image'
      tags:
        - images

  /images/{id}:
    get:
      summary: Get an image by ID
      operationId: getImageById
      parameters:
        - name: id
          in: path
          required: true
          description: ID of the image
          schema:
            type: integer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Image'
      tags:
        - images_by_id

  /passes:
    get:
      summary: Get a list of passes
      operationId: listPasses
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Pass'
      tags:
        - passes

  /passes/{id}:
    get:
      summary: Get a pass by ID
      operationId: getPassById
      parameters:
        - name: id
          in: path
          required: true
          description: ID of the pass
          schema:
            type: integer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MountainPass'
      tags:
        - pass_by_id

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        first_name:
          type: string
        last_name:
          type: string
        surname:
          type: string
        email:
          type: string
        phone_number:
          type: string

    Coordinates:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        latitude:
          type: number
        longitude:
          type: number
        height:
          type: integer

    Image:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        data:
          type: string
        title:
          type: string

    MountainPass:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        beauty_title:
          type: string
        title:
          type: string
        other_titles:
          type: string
        connect:
          type: string
        add_time:
          type: string
          format: date-time
        user:
          $ref: '#/components/schemas/User'
        coords:
          $ref: '#/components/schemas/Coordinates'
        level:
          type: object
          properties:
            winter:
              type: string
            summer:
              type: string
            autumn:
              type: string
            spring:
              type: string
        images:
          type: array
          items:
            $ref: '#/components/schemas/Image'
        status:
          type: string
          enum:
            - new
            - pending
            - accepted
            - rejected